//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DBA_USERS
    {
        public string USERNAME { get; set; }
        public decimal USER_ID { get; set; }
        public string PASSWORD { get; set; }
        public string ACCOUNT_STATUS { get; set; }
        public Nullable<System.DateTime> LOCK_DATE { get; set; }
        public Nullable<System.DateTime> EXPIRY_DATE { get; set; }
        public string DEFAULT_TABLESPACE { get; set; }
        public string TEMPORARY_TABLESPACE { get; set; }
        public System.DateTime CREATED { get; set; }
        public string PROFILE { get; set; }
        public string INITIAL_RSRC_CONSUMER_GROUP { get; set; }
        public string EXTERNAL_NAME { get; set; }
        public string PASSWORD_VERSIONS { get; set; }
        public string EDITIONS_ENABLED { get; set; }
        public string AUTHENTICATION_TYPE { get; set; }
        public string PROXY_ONLY_CONNECT { get; set; }
        public string COMMON { get; set; }
        public Nullable<System.DateTimeOffset> LAST_LOGIN { get; set; }
        public string ORACLE_MAINTAINED { get; set; }
    }
}
