//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DBA_PROFILES
    {
        public string PROFILE { get; set; }
        public string RESOURCE_NAME { get; set; }
        public string RESOURCE_TYPE { get; set; }
        public string LIMIT { get; set; }
        public string COMMON { get; set; }
    }
}
